### ISSUE TITLE
Build is broken on Mac OS

### ISSUE THREAD

**Issue by jbaudanza** [libersys/rtp-ogg-opus#1]
When I try to build on Mac OS, I get the following errors:

```
../src/helpers.cc:130:9: error: cannot use 'throw' with exceptions disabled
        throw std::invalid_argument("Couldn't allocate data buffer.");
        ^
../src/helpers.cc:136:9: error: cannot use 'throw' with exceptions disabled
        throw std::invalid_argument("Couldn't allocate Ogg packet.");
        ^
../src/helpers.cc:160:20: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    char *vendor = "rtp-ogg-opus using libopus";
                   ^
../src/helpers.cc:168:9: error: cannot use 'throw' with exceptions disabled
        throw std::invalid_argument("Couldn't allocate data buffer.");
        ^
../src/helpers.cc:174:9: error: cannot use 'throw' with exceptions disabled
        throw std::invalid_argument("Couldn't allocate Ogg packet.");
        ^
2 warnings and 4 errors generated.
make: *** [Release/obj.target/rtpoggopus/src/helpers.o] Error 1
```

I resolved this by adding the following to binding.gyp:

```js
"conditions": [
    ['OS=="mac"', {
       "xcode_settings": {
          "GCC_ENABLE_CPP_EXCEPTIONS": "YES"
       }
   }]
],
```
I just grabbed this snippet from here, I'm not sure if it's actually a good fix or not. https://github.com/rla/fast-feed/issues/8

I'm using your package to take an RTP stream from mediasoup and package an OGG-Opus stream to send to Google's speach-to-text API. So far it seems to be working great. Thanks!

**Comment by dioris-moreno** [comment]
Hi jbaudanza,

The solution looked good to me. I just added the configuration to binding.gyp and published a new version of rtp-ogg-opus. Thanks for your contribution!

I'm glad the package is being useful to you. I created it for that purpose: streaming Opus to Google's speach-to-text API.

**Comment by jbaudanza** [comment]
@dioris-moreno thank you!

I noticed that libogg seems to write the packets in the order that they are received, and doesn't seem to do much with the `packetno` attribute on the `ogg_packet` struct. 

Do you think it's necessary to run this with some sort of jitter buffer in front to deal with issues of out-of-order or duplicate packets? I realize this would increase the complexity quite a bit.

**Comment by dioris-moreno** [comment]
Hi Jonathan, 

Regarding the out-of-order packets, as I mentioned in README.md, the core of this package is based on opus-tools. The RTP Opus receiving part comes from `opusrtp` (Author: Ralph Giles <giles@thaumas.net>) that states in the BUGS section:

https://opus-codec.org/docs/opus-tools/opusrtp.html
_BUGS
The receive mode does not support out-of-order..._

I only wrapped their code to be able to use it in Node JS, without adding new functionalities.

Regarding duplicated packets, the RFC 7587 “RTP Payload Format for the Opus Speech and Audio Codec” states the following.

_4.1. RTP Header Usage
The receiving side MUST be prepared to receive duplicates of RTP packets. Only one of those payloads MUST be provided to the Opus decoder for decoding and others MUST be discarded._

So, yes, the receiver must take care of duplicated packets before passing them to the OGG-Opus encapsulator. As you mentioned, this would increase complexity quite a bit. The question is: would it be worth it to add that level of complexity? what would be the increase in perceived quality?

I think the duplicated-packets-discard functionality would be easier to implement.
Any ideas on how to implement out-of-order functionality without adding too much complexity?

**Comment by jbaudanza** [comment]
I'm still researching the best way to do this. 

Alternatively, I'm considering piping everything through ffmpeg. Launching an ffmpeg child process seems like overkill to just go from OGG-RTP to OGG-Opus, but implementing all the edge cases in RTP in node seems daunting. For reference, here is ffmpeg's RTP implementation:  https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/rtpdec.c

I'm also not sure how much mediasoup shields me from some of this complexity. Are dropped and out-of-order packets even possible if everything passes through a mediasoup router first? I'm not sure. I'll let you know what I figure out.
